//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sysMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sysMsg() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.sysMsg", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        internal static string balanceRecharge {
            get {
                return ResourceManager.GetString("balanceRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程 的本地化字符串。
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|美容师信息添加失败! 的本地化字符串。
        /// </summary>
        internal static string errAccAdd {
            get {
                return ResourceManager.GetString("errAccAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态变更失败! 的本地化字符串。
        /// </summary>
        internal static string errAccAvailable {
            get {
                return ResourceManager.GetString("errAccAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误！ 的本地化字符串。
        /// </summary>
        internal static string errAccountLogin {
            get {
                return ResourceManager.GetString("errAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，该用户不属于任何门店！ 的本地化字符串。
        /// </summary>
        internal static string errAccountLoginNoBranch {
            get {
                return ResourceManager.GetString("errAccountLoginNoBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容师信息更新失败! 的本地化字符串。
        /// </summary>
        internal static string errAccUpdate {
            get {
                return ResourceManager.GetString("errAccUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加收藏失败! 的本地化字符串。
        /// </summary>
        internal static string errAddFavorite {
            get {
                return ResourceManager.GetString("errAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加服务失败！ 的本地化字符串。
        /// </summary>
        internal static string errAddTreatment {
            get {
                return ResourceManager.GetString("errAddTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回答添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errAnswerAdd {
            get {
                return ResourceManager.GetString("errAnswerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业信息更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errAnswerUpdate {
            get {
                return ResourceManager.GetString("errAnswerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码已被使用! 的本地化字符串。
        /// </summary>
        internal static string errAuthenticationCodeHasUsed {
            get {
                return ResourceManager.GetString("errAuthenticationCodeHasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码已经过期! 的本地化字符串。
        /// </summary>
        internal static string errAuthenticationCodeNotAvailable {
            get {
                return ResourceManager.GetString("errAuthenticationCodeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，请输入正确的验证码！ 的本地化字符串。
        /// </summary>
        internal static string errAuthenticationCodeNotCorrect {
            get {
                return ResourceManager.GetString("errAuthenticationCodeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码发送失败！ 的本地化字符串。
        /// </summary>
        internal static string errAuthenticationCodeSend {
            get {
                return ResourceManager.GetString("errAuthenticationCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额不足! 的本地化字符串。
        /// </summary>
        internal static string errBalanceNotEnough {
            get {
                return ResourceManager.GetString("errBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消订单不能支付! 的本地化字符串。
        /// </summary>
        internal static string errCancelOrderPaid {
            get {
                return ResourceManager.GetString("errCancelOrderPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款金额与订单金额不一致! 的本地化字符串。
        /// </summary>
        internal static string errCantPartPay {
            get {
                return ResourceManager.GetString("errCantPartPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errCartAdd {
            get {
                return ResourceManager.GetString("errCartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errCartDel {
            get {
                return ResourceManager.GetString("errCartDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有购物车已转为订单！ 的本地化字符串。
        /// </summary>
        internal static string errCartHasChangeToOrder {
            get {
                return ResourceManager.GetString("errCartHasChangeToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errCartUpdate {
            get {
                return ResourceManager.GetString("errCartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本公司允许添加人数为0！ 的本地化字符串。
        /// </summary>
        internal static string errComAvailabel0 {
            get {
                return ResourceManager.GetString("errComAvailabel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本公司允许添加人数已经达到最大值！ 的本地化字符串。
        /// </summary>
        internal static string errComAvailabeMax {
            get {
                return ResourceManager.GetString("errComAvailabeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容院信息更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errCompanyUpdate {
            get {
                return ResourceManager.GetString("errCompanyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errCompleteOrder {
            get {
                return ResourceManager.GetString("errCompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改服务状态失败！ 的本地化字符串。
        /// </summary>
        internal static string errCompleteTreatment {
            get {
                return ResourceManager.GetString("errCompleteTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        internal static string errCompleteTreatmentsByCourseID {
            get {
                return ResourceManager.GetString("errCompleteTreatmentsByCourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系详情更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errContactUpdate {
            get {
                return ResourceManager.GetString("errContactUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerAdd {
            get {
                return ResourceManager.GetString("errCustomerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户基本信息更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerBasicUpdate {
            get {
                return ResourceManager.GetString("errCustomerBasicUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerDelete {
            get {
                return ResourceManager.GetString("errCustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户详细信息更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerDetailUpdate {
            get {
                return ResourceManager.GetString("errCustomerDetailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户添加成功！但头像上传失败！！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerImageAdd {
            get {
                return ResourceManager.GetString("errCustomerImageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户信息更新成功！但图片上传失败！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerImageUpdate {
            get {
                return ResourceManager.GetString("errCustomerImageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户等级修改失败! 的本地化字符串。
        /// </summary>
        internal static string errCustomerLevelUpdate {
            get {
                return ResourceManager.GetString("errCustomerLevelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已不存在！ 的本地化字符串。
        /// </summary>
        internal static string errCustomerNotExist {
            get {
                return ResourceManager.GetString("errCustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理数据出现异常! 的本地化字符串。
        /// </summary>
        internal static string errDataError {
            get {
                return ResourceManager.GetString("errDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errDeleteTreatment {
            get {
                return ResourceManager.GetString("errDeleteTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除收藏商品失败! 的本地化字符串。
        /// </summary>
        internal static string errDelFavorite {
            get {
                return ResourceManager.GetString("errDelFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经收藏过了! 的本地化字符串。
        /// </summary>
        internal static string errExistFavorite {
            get {
                return ResourceManager.GetString("errExistFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效时间修改失败! 的本地化字符串。
        /// </summary>
        internal static string errExpirationTimeUpdate {
            get {
                return ResourceManager.GetString("errExpirationTimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像修改失败！ 的本地化字符串。
        /// </summary>
        internal static string errHeadImageUpdate {
            get {
                return ResourceManager.GetString("errHeadImageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errImageDel {
            get {
                return ResourceManager.GetString("errImageDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        internal static string errImageUpload {
            get {
                return ResourceManager.GetString("errImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目增加失败! 的本地化字符串。
        /// </summary>
        internal static string errItemAdd {
            get {
                return ResourceManager.GetString("errItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目删除失败! 的本地化字符串。
        /// </summary>
        internal static string errItemDelete {
            get {
                return ResourceManager.GetString("errItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目修改失败! 的本地化字符串。
        /// </summary>
        internal static string errItemUpdate {
            get {
                return ResourceManager.GetString("errItemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errLevelAdd {
            get {
                return ResourceManager.GetString("errLevelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errLevelDel {
            get {
                return ResourceManager.GetString("errLevelDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errLevelUpdate {
            get {
                return ResourceManager.GetString("errLevelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误！ 的本地化字符串。
        /// </summary>
        internal static string errLogin {
            get {
                return ResourceManager.GetString("errLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的手机号！ 的本地化字符串。
        /// </summary>
        internal static string errLoginMobileError {
            get {
                return ResourceManager.GetString("errLoginMobileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，您所输入的手机不存在！ 的本地化字符串。
        /// </summary>
        internal static string errLoginMobileNotExit {
            get {
                return ResourceManager.GetString("errLoginMobileNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息发送失败！ 的本地化字符串。
        /// </summary>
        internal static string errMessageAdd {
            get {
                return ResourceManager.GetString("errMessageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|本公司没有关于 的本地化字符串。
        /// </summary>
        internal static string errNoAbout {
            get {
                return ResourceManager.GetString("errNoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美丽顾问不正确！ 的本地化字符串。
        /// </summary>
        internal static string errNOAccountID {
            get {
                return ResourceManager.GetString("errNOAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该商品不存在或已下架! 的本地化字符串。
        /// </summary>
        internal static string errNoCommodity {
            get {
                return ResourceManager.GetString("errNoCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据！ 的本地化字符串。
        /// </summary>
        internal static string errNoData {
            get {
                return ResourceManager.GetString("errNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！请确认权限！ 的本地化字符串。
        /// </summary>
        internal static string errNoRole {
            get {
                return ResourceManager.GetString("errNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该服务不存在或已下架! 的本地化字符串。
        /// </summary>
        internal static string errNoService {
            get {
                return ResourceManager.GetString("errNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|请先设置销售步骤！ 的本地化字符串。
        /// </summary>
        internal static string errNoStep {
            get {
                return ResourceManager.GetString("errNoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有收藏过此商品! 的本地化字符串。
        /// </summary>
        internal static string errNotExistFavorite {
            get {
                return ResourceManager.GetString("errNotExistFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有Ecard支付权限 的本地化字符串。
        /// </summary>
        internal static string errNotHaveEcardPayRole {
            get {
                return ResourceManager.GetString("errNotHaveEcardPayRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码错误! 的本地化字符串。
        /// </summary>
        internal static string errOldPassword {
            get {
                return ResourceManager.GetString("errOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加需求失败! 的本地化字符串。
        /// </summary>
        internal static string errOppAdd {
            get {
                return ResourceManager.GetString("errOppAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除需求失败! 的本地化字符串。
        /// </summary>
        internal static string errOppDel {
            get {
                return ResourceManager.GetString("errOppDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有需求已转为订单！ 的本地化字符串。
        /// </summary>
        internal static string errOppHasChangeToOrder {
            get {
                return ResourceManager.GetString("errOppHasChangeToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新需求失败! 的本地化字符串。
        /// </summary>
        internal static string errOppUpdate {
            get {
                return ResourceManager.GetString("errOppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单添加失败! 的本地化字符串。
        /// </summary>
        internal static string errOrderAdd {
            get {
                return ResourceManager.GetString("errOrderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认失败！ 的本地化字符串。
        /// </summary>
        internal static string errOrderConfirm {
            get {
                return ResourceManager.GetString("errOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单取消失败! 的本地化字符串。
        /// </summary>
        internal static string errOrderDelete {
            get {
                return ResourceManager.GetString("errOrderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单状态已无法更新！ 的本地化字符串。
        /// </summary>
        internal static string errOrderEdit {
            get {
                return ResourceManager.GetString("errOrderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付失败，订单已经支付！ 的本地化字符串。
        /// </summary>
        internal static string errOrderHasPaid {
            get {
                return ResourceManager.GetString("errOrderHasPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新订单失败! 的本地化字符串。
        /// </summary>
        internal static string errOrderUpdate {
            get {
                return ResourceManager.GetString("errOrderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|部位增加失败! 的本地化字符串。
        /// </summary>
        internal static string errPartAdd {
            get {
                return ResourceManager.GetString("errPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|部位删除失败! 的本地化字符串。
        /// </summary>
        internal static string errPartDelete {
            get {
                return ResourceManager.GetString("errPartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|部位更新失败! 的本地化字符串。
        /// </summary>
        internal static string errPartUpdate {
            get {
                return ResourceManager.GetString("errPartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误！ 的本地化字符串。
        /// </summary>
        internal static string errPasswordNotCorrect {
            get {
                return ResourceManager.GetString("errPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付失败! 的本地化字符串。
        /// </summary>
        internal static string errPay {
            get {
                return ResourceManager.GetString("errPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格已变化！ 的本地化字符串。
        /// </summary>
        internal static string errPriceHasChanged {
            get {
                return ResourceManager.GetString("errPriceHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度变更失败! 的本地化字符串。
        /// </summary>
        internal static string errProgressUpdate {
            get {
                return ResourceManager.GetString("errProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|促销信息增加失败! 的本地化字符串。
        /// </summary>
        internal static string errPromotionAdd {
            get {
                return ResourceManager.GetString("errPromotionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|促销信息删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errPromotionDel {
            get {
                return ResourceManager.GetString("errPromotionDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|促销信息更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errPromotionUpdate {
            get {
                return ResourceManager.GetString("errPromotionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品数量不足！ 的本地化字符串。
        /// </summary>
        internal static string errQuantityNotSufficient {
            get {
                return ResourceManager.GetString("errQuantityNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|问卷添加失败! 的本地化字符串。
        /// </summary>
        internal static string errQuestionAdd {
            get {
                return ResourceManager.GetString("errQuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|问卷更新失败! 的本地化字符串。
        /// </summary>
        internal static string errQuestionUpt {
            get {
                return ResourceManager.GetString("errQuestionUpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录添加失败! 的本地化字符串。
        /// </summary>
        internal static string errRecAdd {
            get {
                return ResourceManager.GetString("errRecAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errRecDel {
            get {
                return ResourceManager.GetString("errRecDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录更新失败! 的本地化字符串。
        /// </summary>
        internal static string errRecUpdate {
            get {
                return ResourceManager.GetString("errRecUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errReviewAdd {
            get {
                return ResourceManager.GetString("errReviewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评价不能为空！ 的本地化字符串。
        /// </summary>
        internal static string errReviewEmpty {
            get {
                return ResourceManager.GetString("errReviewEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errReviewUpdate {
            get {
                return ResourceManager.GetString("errReviewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|服务增加失败! 的本地化字符串。
        /// </summary>
        internal static string errServiceAdd {
            get {
                return ResourceManager.GetString("errServiceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|服务删除失败! 的本地化字符串。
        /// </summary>
        internal static string errServiceDelete {
            get {
                return ResourceManager.GetString("errServiceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务详情更新失败! 的本地化字符串。
        /// </summary>
        internal static string errServiceDetailUpdate {
            get {
                return ResourceManager.GetString("errServiceDetailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|服务更新失败! 的本地化字符串。
        /// </summary>
        internal static string errServiceUpdate {
            get {
                return ResourceManager.GetString("errServiceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|个人基本信息设置失败! 的本地化字符串。
        /// </summary>
        internal static string errSettingCustomer {
            get {
                return ResourceManager.GetString("errSettingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤数请输入0至 的本地化字符串。
        /// </summary>
        internal static string errStepInputNumber {
            get {
                return ResourceManager.GetString("errStepInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|提交失败! 的本地化字符串。
        /// </summary>
        internal static string errSubmit {
            get {
                return ResourceManager.GetString("errSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陈伟林!!! 的本地化字符串。
        /// </summary>
        internal static string errSystemHandle {
            get {
                return ResourceManager.GetString("errSystemHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板添加失败！ 的本地化字符串。
        /// </summary>
        internal static string errTemplateAdd {
            get {
                return ResourceManager.GetString("errTemplateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板删除失败！ 的本地化字符串。
        /// </summary>
        internal static string errTemplateDel {
            get {
                return ResourceManager.GetString("errTemplateDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errTemplateUpdate {
            get {
                return ResourceManager.GetString("errTemplateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此服务已无法更新！ 的本地化字符串。
        /// </summary>
        internal static string errTreatmentEdit {
            get {
                return ResourceManager.GetString("errTreatmentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单下已有完成的服务，不能取消！ 的本地化字符串。
        /// </summary>
        internal static string errTreatmentHasCompleted {
            get {
                return ResourceManager.GetString("errTreatmentHasCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改失败！ 的本地化字符串。
        /// </summary>
        internal static string errUpdatePassword {
            get {
                return ResourceManager.GetString("errUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新责任人失败！ 的本地化字符串。
        /// </summary>
        internal static string errUpdateResponsiblePerson {
            get {
                return ResourceManager.GetString("errUpdateResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改订单价格失败! 的本地化字符串。
        /// </summary>
        internal static string errUpdateSalePriceDelete {
            get {
                return ResourceManager.GetString("errUpdateSalePriceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单下已有完成的服务,不能修改价格! 的本地化字符串。
        /// </summary>
        internal static string errUpdateSalePriceHasCompleted {
            get {
                return ResourceManager.GetString("errUpdateSalePriceHasCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errUpdateTreatment {
            get {
                return ResourceManager.GetString("errUpdateTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改指定失败！ 的本地化字符串。
        /// </summary>
        internal static string errUpdateTreatmentDesignated {
            get {
                return ResourceManager.GetString("errUpdateTreatmentDesignated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务备注更新失败！ 的本地化字符串。
        /// </summary>
        internal static string errUpdateTreatmentRemark {
            get {
                return ResourceManager.GetString("errUpdateTreatmentRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在该名字！ 的本地化字符串。
        /// </summary>
        internal static string existCustomerName {
            get {
                return ResourceManager.GetString("existCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字与联系电话已存在! 的本地化字符串。
        /// </summary>
        internal static string existCustomerNameAndPhone {
            get {
                return ResourceManager.GetString("existCustomerNameAndPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在该联系电话！ 的本地化字符串。
        /// </summary>
        internal static string existCustomerPhone {
            get {
                return ResourceManager.GetString("existCustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该手机号码已经存在！ 的本地化字符串。
        /// </summary>
        internal static string existMobileError {
            get {
                return ResourceManager.GetString("existMobileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您有一条来自{0}的新消息！请注意查收！ 的本地化字符串。
        /// </summary>
        internal static string newMsg {
            get {
                return ResourceManager.GetString("newMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您有一条来自{0}的提醒！请注意查收！ 的本地化字符串。
        /// </summary>
        internal static string newRemind {
            get {
                return ResourceManager.GetString("newRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        internal static string rechargeBalanceError {
            get {
                return ResourceManager.GetString("rechargeBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        internal static string rechargeBalanceSuccess {
            get {
                return ResourceManager.GetString("rechargeBalanceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有一个预约! 的本地化字符串。
        /// </summary>
        internal static string remindAppoint {
            get {
                return ResourceManager.GetString("remindAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您在 的本地化字符串。
        /// </summary>
        internal static string remindYou {
            get {
                return ResourceManager.GetString("remindYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 之间! 的本地化字符串。
        /// </summary>
        internal static string strBetween {
            get {
                return ResourceManager.GetString("strBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的产品! 的本地化字符串。
        /// </summary>
        internal static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|美容师信息添加成功! 的本地化字符串。
        /// </summary>
        internal static string sucAccAdd {
            get {
                return ResourceManager.GetString("sucAccAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态变更成功! 的本地化字符串。
        /// </summary>
        internal static string sucAccAvailable {
            get {
                return ResourceManager.GetString("sucAccAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容师信息更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucAccUpdate {
            get {
                return ResourceManager.GetString("sucAccUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回答添加成功！ 的本地化字符串。
        /// </summary>
        internal static string sucAnswerAdd {
            get {
                return ResourceManager.GetString("sucAnswerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业信息更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucAnswerUpdate {
            get {
                return ResourceManager.GetString("sucAnswerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码发送成功！ 的本地化字符串。
        /// </summary>
        internal static string sucAuthenticationCodeSend {
            get {
                return ResourceManager.GetString("sucAuthenticationCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCartAdd {
            get {
                return ResourceManager.GetString("sucCartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCartDel {
            get {
                return ResourceManager.GetString("sucCartDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCartUpdate {
            get {
                return ResourceManager.GetString("sucCartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容院信息更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucCompanyUpdate {
            get {
                return ResourceManager.GetString("sucCompanyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCompleteTreatmentsByCourseID {
            get {
                return ResourceManager.GetString("sucCompleteTreatmentsByCourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系详情更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucContactUpdate {
            get {
                return ResourceManager.GetString("sucContactUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户添加成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCustomerAdd {
            get {
                return ResourceManager.GetString("sucCustomerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户基本信息更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCustomerBasicUpdate {
            get {
                return ResourceManager.GetString("sucCustomerBasicUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户删除成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCustomerDelete {
            get {
                return ResourceManager.GetString("sucCustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户详细信息更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucCustomerDetailUpdate {
            get {
                return ResourceManager.GetString("sucCustomerDetailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户等级修改成功! 的本地化字符串。
        /// </summary>
        internal static string sucCustomerLevelUpdate {
            get {
                return ResourceManager.GetString("sucCustomerLevelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效时间修改成功! 的本地化字符串。
        /// </summary>
        internal static string sucExpirationTimeUpdate {
            get {
                return ResourceManager.GetString("sucExpirationTimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像修改成功！ 的本地化字符串。
        /// </summary>
        internal static string sucHeadImageUpdate {
            get {
                return ResourceManager.GetString("sucHeadImageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片删除成功！ 的本地化字符串。
        /// </summary>
        internal static string sucImageDel {
            get {
                return ResourceManager.GetString("sucImageDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        internal static string sucImageUpload {
            get {
                return ResourceManager.GetString("sucImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|项目增加成功! 的本地化字符串。
        /// </summary>
        internal static string sucItemAdd {
            get {
                return ResourceManager.GetString("sucItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|项目删除成功! 的本地化字符串。
        /// </summary>
        internal static string sucItemDelete {
            get {
                return ResourceManager.GetString("sucItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|项目修改成功! 的本地化字符串。
        /// </summary>
        internal static string sucItemUpdate {
            get {
                return ResourceManager.GetString("sucItemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡添加成功! 的本地化字符串。
        /// </summary>
        internal static string sucLevelAdd {
            get {
                return ResourceManager.GetString("sucLevelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡删除成功! 的本地化字符串。
        /// </summary>
        internal static string sucLevelDel {
            get {
                return ResourceManager.GetString("sucLevelDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员卡更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucLevelUpdate {
            get {
                return ResourceManager.GetString("sucLevelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|登陆成功! 的本地化字符串。
        /// </summary>
        internal static string sucLogin {
            get {
                return ResourceManager.GetString("sucLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息发送成功！ 的本地化字符串。
        /// </summary>
        internal static string sucMessageAdd {
            get {
                return ResourceManager.GetString("sucMessageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加需求成功! 的本地化字符串。
        /// </summary>
        internal static string sucOppAdd {
            get {
                return ResourceManager.GetString("sucOppAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除需求成功! 的本地化字符串。
        /// </summary>
        internal static string sucOppDel {
            get {
                return ResourceManager.GetString("sucOppDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新需求成功! 的本地化字符串。
        /// </summary>
        internal static string sucOppUpdate {
            get {
                return ResourceManager.GetString("sucOppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单添加成功! 的本地化字符串。
        /// </summary>
        internal static string sucOrderAdd {
            get {
                return ResourceManager.GetString("sucOrderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认成功！ 的本地化字符串。
        /// </summary>
        internal static string sucOrderConfirm {
            get {
                return ResourceManager.GetString("sucOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单取消成功! 的本地化字符串。
        /// </summary>
        internal static string sucOrderDelete {
            get {
                return ResourceManager.GetString("sucOrderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新订单成功! 的本地化字符串。
        /// </summary>
        internal static string sucOrderUpdate {
            get {
                return ResourceManager.GetString("sucOrderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|部位增加成功! 的本地化字符串。
        /// </summary>
        internal static string sucPartAdd {
            get {
                return ResourceManager.GetString("sucPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|部位删除成功! 的本地化字符串。
        /// </summary>
        internal static string sucPartDelete {
            get {
                return ResourceManager.GetString("sucPartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|部位更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucPartUpdate {
            get {
                return ResourceManager.GetString("sucPartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码发送成功！ 的本地化字符串。
        /// </summary>
        internal static string sucPasswordSend {
            get {
                return ResourceManager.GetString("sucPasswordSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功! 的本地化字符串。
        /// </summary>
        internal static string sucPasswordUpdate {
            get {
                return ResourceManager.GetString("sucPasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付成功！ 的本地化字符串。
        /// </summary>
        internal static string sucPay {
            get {
                return ResourceManager.GetString("sucPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度变更成功! 的本地化字符串。
        /// </summary>
        internal static string sucProgressUpdate {
            get {
                return ResourceManager.GetString("sucProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|促销信息增加成功! 的本地化字符串。
        /// </summary>
        internal static string sucPromotionAdd {
            get {
                return ResourceManager.GetString("sucPromotionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|促销信息删除成功! 的本地化字符串。
        /// </summary>
        internal static string sucPromotionDel {
            get {
                return ResourceManager.GetString("sucPromotionDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|促销信息更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucPromotionUpdate {
            get {
                return ResourceManager.GetString("sucPromotionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|问卷添加成功! 的本地化字符串。
        /// </summary>
        internal static string sucQuestionAdd {
            get {
                return ResourceManager.GetString("sucQuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|问卷更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucQuestionUpt {
            get {
                return ResourceManager.GetString("sucQuestionUpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录添加成功! 的本地化字符串。
        /// </summary>
        internal static string sucRecAdd {
            get {
                return ResourceManager.GetString("sucRecAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录删除成功！ 的本地化字符串。
        /// </summary>
        internal static string sucRecDel {
            get {
                return ResourceManager.GetString("sucRecDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美容记录更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucRecUpdate {
            get {
                return ResourceManager.GetString("sucRecUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论添加成功！ 的本地化字符串。
        /// </summary>
        internal static string sucReviewAdd {
            get {
                return ResourceManager.GetString("sucReviewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucReviewUpdate {
            get {
                return ResourceManager.GetString("sucReviewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|服务增加成功! 的本地化字符串。
        /// </summary>
        internal static string sucServiceAdd {
            get {
                return ResourceManager.GetString("sucServiceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|服务删除成功! 的本地化字符串。
        /// </summary>
        internal static string sucServiceDelete {
            get {
                return ResourceManager.GetString("sucServiceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务详情更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucServiceDetailUpdate {
            get {
                return ResourceManager.GetString("sucServiceDetailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|服务更新成功! 的本地化字符串。
        /// </summary>
        internal static string sucServiceUpdate {
            get {
                return ResourceManager.GetString("sucServiceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|个人基本信息设置成功! 的本地化字符串。
        /// </summary>
        internal static string sucSettingCustomer {
            get {
                return ResourceManager.GetString("sucSettingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|提交成功! 的本地化字符串。
        /// </summary>
        internal static string sucSubmit {
            get {
                return ResourceManager.GetString("sucSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板添加成功！ 的本地化字符串。
        /// </summary>
        internal static string sucTemplateAdd {
            get {
                return ResourceManager.GetString("sucTemplateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板删除成功！ 的本地化字符串。
        /// </summary>
        internal static string sucTemplateDel {
            get {
                return ResourceManager.GetString("sucTemplateDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板更新成功！ 的本地化字符串。
        /// </summary>
        internal static string sucTemplateUpdate {
            get {
                return ResourceManager.GetString("sucTemplateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改订单价格成功! 的本地化字符串。
        /// </summary>
        internal static string sucUpdateTotalSalePrice {
            get {
                return ResourceManager.GetString("sucUpdateTotalSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改指定成功！ 的本地化字符串。
        /// </summary>
        internal static string sucUpdateTreatmentDesignated {
            get {
                return ResourceManager.GetString("sucUpdateTreatmentDesignated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
